export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const NO_FILTER_ALL_POST_REQUEST = "NO_FILTER_ALL_POST_REQUEST";
export const NO_FILTER_ALL_POST_SUCCESS = "NO_FILTER_ALL_POST_SUCCESS";
export const NO_FILTER_ALL_POST_FAIL = "NO_FILTER_ALL_POST_FAIL";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_RESET = "NEW_POST_RESET";
export const NEW_POST_FAIL = "NEW_POST_FAIL";

export const MY_POSTS_REQUEST = "MY_POSTS_REQUEST";
export const MY_POSTS_SUCCESS = "MY_POSTS_SUCCESS";
export const MY_POSTS_FAIL = "MY_POSTS_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_RESET = "DELETE_POST_RESET";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_RESET = "UPDATE_POST_RESET";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL"; 

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 