export const ALL_RESOURCE_REQUEST = "ALL_RESOURCE_REQUEST";
export const ALL_RESOURCE_SUCCESS = "ALL_RESOURCE_SUCCESS";
export const ALL_RESOURCE_FAIL = "ALL_RESOURCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 