export const ALL_RESOURCE_REQUEST = "ALL_RESOURCE_REQUEST";
export const ALL_RESOURCE_SUCCESS = "ALL_RESOURCE_SUCCESS";
export const ALL_RESOURCE_FAIL = "ALL_RESOURCE_FAIL";

export const NO_FILTER_ALL_RESOURCE_REQUEST = "NO_FILTER_ALL_RESOURCE_REQUEST";
export const NO_FILTER_ALL_RESOURCE_SUCCESS = "NO_FILTER_ALL_RESOURCE_SUCCESS";
export const NO_FILTER_ALL_RESOURCE_FAIL = "NO_FILTER_ALL_RESOURCE_FAIL";

export const NEW_RESOURCE_REQUEST = "NEW_RESOURCE_REQUEST";
export const NEW_RESOURCE_SUCCESS = "NEW_RESOURCE_SUCCESS";
export const NEW_RESOURCE_RESET = "NEW_RESOURCE_RESET";
export const NEW_RESOURCE_FAIL = "NEW_RESOURCE_FAIL";

export const MY_RESOURCES_REQUEST = "MY_RESOURCES_REQUEST";
export const MY_RESOURCES_SUCCESS = "MY_RESOURCES_SUCCESS";
export const MY_RESOURCES_FAIL = "MY_RESOURCES_FAIL";

export const DELETE_RESOURCE_REQUEST = "DELETE_RESOURCE_REQUEST";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_RESET = "DELETE_RESOURCE_RESET";
export const DELETE_RESOURCE_FAIL = "DELETE_RESOURCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 