export const ALL_RESOURCE_REQUEST = "ALL_RESOURCE_REQUEST";
export const ALL_RESOURCE_SUCCESS = "ALL_RESOURCE_SUCCESS";
export const ALL_RESOURCE_FAIL = "ALL_RESOURCE_FAIL";

export const NEW_RESOURCE_REQUEST = "NEW_RESOURCE_REQUEST";
export const NEW_RESOURCE_SUCCESS = "NEW_RESOURCE_SUCCESS";
export const NEW_RESOURCE_RESET = "NEW_RESOURCE_RESET";
export const NEW_RESOURCE_FAIL = "NEW_RESOURCE_FAIL";

export const MY_RESOURCES_REQUEST = "MY_RESOURCES_REQUEST";
export const MY_RESOURCES_SUCCESS = "MY_RESOURCES_SUCCESS";
export const MY_RESOURCES_FAIL = "MY_RESOURCES_FAIL";

export const UPDATE_RESOURCE_REQUEST = "UPDATE_RESOURCE_REQUEST";
export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS";
export const UPDATE_RESOURCE_RESET = "UPDATE_RESOURCE_RESET";
export const UPDATE_RESOURCE_FAIL = "UPDATE_RESOURCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 